     <TABLE id=footer cellSpacing=2 cellPadding=0 width="100%" border=0>
        <TR>
          <TD colSpan=15><IMG height=8 alt="" 
            src="/pirwww/images/sss/footer_bar.gif" width="100%"></TD></TR>
        <TR>
          <TD>
            <TABLE cellSpacing=0 cellPadding=0 width="100%" align=left 
              border=0>
              <TR>
                <TD><IMG height=21 alt="" src="/pirwww/images/transparent_dot.png" 
                  width=100> </TD>




                <TD><A 
                  onmouseover="changeImages('footer_login', '/pirwww/images/sss/footer_login-over.gif'); return true;" 
                  onmouseout="changeImages('footer_login', '/pirwww/images/sss/footer_login.gif'); return true;" 
                  href="http://www.proteomicsresource.org/ProteomicsPortal/"><IMG alt=Login 
                  src="/pirwww/images/sss/footer_login.gif" border=0 
                  name=footer_login></A></TD>
                <TD><IMG alt="" src="/pirwww/images/transparent_dot.png" width=20></TD>












                <TD><A 
                  onmouseover="changeImages('footer_home', '/pirwww/images/sss/footer_home-over.gif'); return true;" 
                  onmouseout="changeImages('footer_home', '/pirwww/images/sss/footer_home.gif'); return true;" 
                  href="http://www.proteomicsresource.org/"><IMG alt=Home 
                  src="/pirwww/images/sss/footer_home.gif" border=0 
                  name=footer_home></A></TD>
                <TD><IMG alt="" src="/pirwww/images/transparent_dot.png" width=20></TD>
                <TD><A 
                  onmouseover="changeImages('footer_contact', '/pirwww/images/sss/footer_contact-over.gif'); return true;" 
                  onmouseout="changeImages('footer_contact', '/pirwww/images/sss/footer_contact.gif'); return true;" 
                  href="http://www.proteomicsresource.org/contact.aspx"><IMG 
                  alt=Contact src="/pirwww/images/sss/footer_contact.gif" border=0 
                  name=footer_contact></A></TD>
                <TD width=50%></TD>
                <TD><IMG height=21 alt="" src="/pirwww/images/transparent_dot.png" 
                  width=360></TD>
                <TD><A 
                  onmouseover="changeImages('footer_niaid', '/pirwww/images/sss/footer_niaid-over.gif'); return true;" 
                  onmouseout="changeImages('footer_niaid', '/pirwww/images/sss/footer_niaid.gif'); return true;" 
                  href="http://www.niaid.nih.gov/default.htm" target=_blank><IMG 
                  alt='National Institute of Allergy and Infectious Disease' src="/pirwww/images/sss/footer_niaid.gif" border=0 
                  name=footer_niaid></A></TD>
                <TD><IMG alt="" src="/pirwww/images/transparent_dot.png" width=20></TD>
                <TD><A 
                  onmouseover="changeImages('footer_nih', '/pirwww/images/sss/footer_nih-over.gif'); return true;" 
                  onmouseout="changeImages('footer_nih', '/pirwww/images/sss/footer_nih.gif'); return true;" 
                  href="http://www.nih.gov/" target=_blank><IMG alt='National Institutes of Health' 
                  src="/pirwww/images/sss/footer_nih.gif" border=0 
                  name=footer_nih></A></TD>
                <TD><IMG alt="" src="/pirwww/images/transparent_dot.png" width=20></TD>
                <TD><A 
                  onmouseover="changeImages('footer_dhhs', '/pirwww/images/sss/footer_dhhs-over.gif'); return true;" 
                  onmouseout="changeImages('footer_dhhs', '/pirwww/images/sss/footer_dhhs.gif'); return true;" 
                  href="http://www.os.dhhs.gov/" target=_blank><IMG alt='Department of Health and Human Services' 
                  src="/pirwww/images/sss/footer_dhhs.gif" border=0 
                  name=footer_dhhs></A></TD>
                <TD><IMG height=21 alt="" src="/pirwww/images/transparent_dot.png" 
                  width=150></TD></TR></TABLE>
</TD></TR></TABLE><br><br>
<SCRIPT LANGUAGE="JAVASCRIPT">
<!--
function changeImages(img_name, img_src) {
   document[img_name].src = img_src;
}
//-->
</SCRIPT>

